<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dictionary["House"] = array (
    'table' => 'houses',
    'audited' => true,
    'fields' => array (
        'type' => array (
            'name'     => 'type',
            'type'     => 'enum',
            'vname'    => 'LBL_TYPE',
            'options'  => 'houses_types_dom',
            'len'      => '60',
            'required' => true,
            'audited'  => true,
        ),
        'region' => array (
            'name'     => 'region',
            'type'     => 'varchar',
            'vname'    => 'LBL_REGION',
            'len'      => '255',
            'required' => false,
            'audited'  => true,
        ),
        'city' => array (
            'name'     => 'city',
            'type'     => 'varchar',
            'vname'    => 'LBL_CITY',
            'len'      => '255',
            'required' => false,
            'audited'  => true,
        ),
        'street' => array (
            'name'     => 'street',
            'type'     => 'varchar',
            'vname'    => 'LBL_STREET',
            'len'      => '255',
            'required' => true,
            'audited'  => true,
        ),
        'house' => array (
            'name'     => 'house',
            'type'     => 'varchar',
            'vname'    => 'LBL_HOUSE',
            'len'      => '255',
            'required' => true,
            'audited'  => true,
        ),
        'serialnum' => array (
          'name'     => 'serialnum',
          'type'     => 'varchar',
          'vname'    => 'LBL_SERIALNUM',
          'len'      => '30',
          'required' => false,
          'audited'  => true,
          ),
        'build_date' => array (
          'name'     => 'build_date',
          'type'     => 'date',
          'vname'    => 'LBL_BUILD_DATE',
          'len'      => '30',
          'required' => false,
          'audited'  => true,
          ),
        'start_date' => array (
          'name'     => 'start_date',
          'type'     => 'date',
          'vname'    => 'LBL_START_DATE',
          'len'      => '30',
          'required' => false,
          'audited'  => true,
          ),
        'stages_max' => array (
          'name'     => 'stages_max',
          'type'     => 'int',
          'vname'    => 'LBL_STAGES_MAX',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0', 'max' => '500'),
          ),
        'stages_min' => array (
          'name'     => 'stages_min',
          'type'     => 'int',
          'vname'    => 'LBL_STAGES_MIN',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0', 'max' => '500'),
          ),
        'livinig_premises' => array (
          'name'     => 'living_premises',
          'type'     => 'int',
          'vname'    => 'LBL_LIVING_PREMISES',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0', 'max' => '5000'),
          ),
        'nonlivinig_premises' => array (
          'name'     => 'nonliving_premises',
          'type'     => 'int',
          'vname'    => 'LBL_NONLIVING_PREMISES',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0', 'max' => '5000'),
          ),
        'heating' =>
        array (
          'name' => 'heating',
          'vname' => 'LBL_HEATING',
          'type' => 'enum',
          'options' => 'heating_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'sewarage' =>
        array (
          'name' => 'sewarage',
          'vname' => 'LBL_SEWARAGE',
          'type' => 'enum',
          'options' => 'sewarage_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'cold_water_supply' =>
        array (
          'name' => 'cold_water_supply',
          'vname' => 'LBL_COLD_WATER_SUPPLY',
          'type' => 'enum',
          'options' => 'cold_water_supply_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'hot_water_supply' =>
        array (
          'name' => 'hot_water_supply',
          'vname' => 'LBL_HOT_WATER_SUPPLY',
          'type' => 'enum',
          'options' => 'hot_water_supply_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'water_heater_type' =>
        array (
          'name' => 'water_heater_type',
          'vname' => 'LBL_WATER_HEATER_TYPES',
          'type' => 'enum',
          'options' => 'water_heater_types_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'gas_supply' =>
        array (
          'name' => 'gas_supply',
          'vname' => 'LBL_GAS_SUPPLY',
          'type' => 'enum',
          'options' => 'gas_supply_types_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'cooker_type' =>
        array (
          'name' => 'cooker_type',
          'vname' => 'LBL_COOKER_TYPE',
          'type' => 'enum',
          'options' => 'cooker_types_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'bath_presence' =>
        array (
          'name' => 'bath_presence',
          'vname' => 'LBL_BATH_PRESENCE',
          'type' => 'enum',
          'options' => 'presence_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'rubbish_chute_presence' =>
        array (
          'name' => 'rubbish_chute_presence',
          'vname' => 'LBL_RUBBISH_CHUTE_PRESENCE',
          'type' => 'enum',
          'options' => 'presence_dom',
          'len' => 100,
          'importable' => 'required',
        ),
        'total_area' => array (
          'name'     => 'total_area',
          'type'     => 'float',
          'dbType'   => 'double',
          'vname'    => 'LBL_TOTAL_AREA',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0'),
          ),
        'living_premises_area' => array (
          'name'     => 'living_premises_area',
          'type'     => 'float',
          'dbType'   => 'double',
          'vname'    => 'LBL_LIVING_PREMISES_AREA',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0'),
          ),
        'nonliving_premises_area' => array (
          'name'     => 'nonliving_premises_area',
          'type'     => 'float',
          'dbType'   => 'double',
          'vname'    => 'LBL_NONLIVING_PREMISES_AREA',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0'),
          ),
        'total_premises_area' => array (
          'name'     => 'total_premises_area',
          'type'     => 'float',
          'dbType'   => 'double',
          'vname'    => 'LBL_TOTAL_PREMISES_AREA',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0'),
          ),
        'total_property_area' => array (
          'name'     => 'total_property_area',
          'type'     => 'float',
          'dbType'   => 'double',
          'vname'    => 'LBL_TOTAL_PROPERTY_AREA',
          'len'      => '5',
          'required' => false,
          'audited'  => true,
          'validation' => array ('type' => 'range', 'min' => '0'),
          ),
    ),
    'relationships' => array (
    ),
    'optimistic_lock' => true,
);

require_once('include/SugarObjects/VardefManager.php');
VardefManager::createVardef('Houses', 'House', array('basic', 'assignable'));
?>
